### ISSUE TITLE
MediaCodecVideoDecoder$DecoderOutputBufferInfo  notFound

### ISSUE THREAD

**Issue by sr71k** [nubomedia-vtt/webrtcpeer-android#2]
When i want to build my project from source,i got the error "java.lang.NoClassDefFoundError: org/webrtc/MediaCodecVideoDecoder$DecoderOutputBufferInfo"  but  i  found there is no class "DecoderOutputBufferInfo" in  the library "io.pristine:libjingle:11139@aar" however
"DecodedOutputBuffer" ,  What should i do ?@jpsjanne
`08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err: java.lang.NoClassDefFoundError: org/webrtc/MediaCodecVideoDecoder$DecoderOutputBufferInfo
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at java.lang.Runtime.nativeLoad(Native Method)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at java.lang.Runtime.doLoad(Runtime.java:421)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:362)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at java.lang.System.loadLibrary(System.java:526)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at org.webrtc.Logging.<clinit>(Logging.java:27)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at org.webrtc.VideoRendererGui.setView(VideoRendererGui.java:416)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at fi.vtt.nubotest.PeerVideoActivity.onCreate(PeerVideoActivity.java:177)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at android.app.Activity.performCreate(Activity.java:5303)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1091)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:142)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at android.os.Looper.loop(Looper.java:136)
08-26 16:19:23.770 20225-20225/fi.vtt.nubotest W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5217)
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err:     at dalvik.system.NativeStart.main(Native Method)
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.webrtc.MediaCodecVideoDecoder$DecoderOutputBufferInfo" on path: DexPathList[[zip file "/data/app/fi.vtt.nubotest-2.apk"],nativeLibraryDirectories=[/data/app-lib/fi.vtt.nubotest-2, /vendor/lib, /system/lib]]
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest W/System.err:    ... 21 more
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest E/rtc: #
                                                      # Fatal error in ../../talk/app/webrtc/java/jni/classreferenceholder.cc, line 136
                                                      # Check failed: !jni->ExceptionCheck()
                                                      # error during FindClass: org/webrtc/MediaCodecVideoDecoder$DecoderOutputBufferInfo
                                                      #
08-26 16:19:23.780 20225-20225/fi.vtt.nubotest A/libc: Fatal signal 6 (SIGABRT) at 0x00004f01 (code=-6), thread 20225 (fi.vtt.nubotest)`

**Comment by sr71k** [comment]
@jpsjanne

**Comment by jpsjanne** [comment]
Hi, sorry for the late response, I was on a holiday. Please pull a new revision of nubo-test and try rebuilding again.

The problem is that we mitigated from a locally built libjingle to Maven dependency. The version in Maven is older, thus missing some code like the DecoderOutputBufferInfo class. While the Maven dependency seems okay, the project still seems to attempt to load native code from a local .so file. I removed the file, so let's see if it has any effect.

**Comment by sr71k** [comment]
Thank you!!!  It works!  
 I'm sorry to interrupt your holiday.
